# Generated by Django 4.2.7 on 2023-12-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmigrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringtes', models.CharField(max_length=200)),
            ],
        ),
    ]
